### ISSUE TITLE
I got error like "No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code."

### ISSUE THREAD

**Issue by humorless** [minimal-xyz/minimal-shadow-cljs-nodejs#3]
I downloaded this template. 
1.  `yarn shadow-cljs cljs-repl app`
2.  I used a browser to connect. 
3. The prompt changed to REPL prompt.

However, when I gave command like `(+ 1 2)` on the cljs REPL, I got error message like `No application has connected to the REPL server. Make sure your JS environment has loaded your compiled ClojureScript code.`

**Comment by thheller** [comment]
The `:app` build generates a `target/main.js`. You need to run this manually (ie. `node target/main.js`), once running you can connect the REPL.

Alternatively just run `yarn shadow-cljs node-repl`. That takes core of launching the node process and provides the REPL.

**Comment by humorless** [comment]
It works! Thank you a lot.
